# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Evenement')),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'evenement")),
                ('jour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jour')),
                ('heure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heure')),
                ('hDebut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heure de Début')),
                ('hFin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heure de Fin ')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Contact')),
                ('nbreParticipants', models.IntegerField(blank=True, null=True, verbose_name=' Nbre de Participants')),
                ('bureau', models.IntegerField(blank=True, null=True, verbose_name='Membres du Bureau présents')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Rapport de la réunion')),
                ('odd1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 1')),
                ('odd2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 2')),
                ('odd3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 3')),
                ('odd4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 4')),
                ('odd5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 5')),
                ('odd6', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 6')),
                ('odd7', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 7')),
                ('odd8', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 8')),
                ('odd9', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 9')),
                ('odd10', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 10')),
            ],
            options={
                'verbose_name_plural': 'Evenements',
            },
        ),
    ]
