# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0003_auto_20171124_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='annee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Année'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='mois',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mois'),
        ),
    ]
