# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0004_auto_20171124_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre')),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('dateCreation', models.DateField(verbose_name="Date de l'evenement")),
                ('jour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jour')),
                ('mois', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mois')),
                ('annee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Année')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Contact')),
                ('annonce', models.TextField(blank=True, null=True, verbose_name='Annonce')),
            ],
            options={
                'verbose_name_plural': 'Annonces',
            },
        ),
    ]
