# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0007_auto_20171124_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaires',
            options={'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='sujetforum',
            options={'verbose_name_plural': 'Sujets_Forum'},
        ),
        migrations.AlterModelOptions(
            name='themeforum',
            options={'verbose_name_plural': 'Themes_Forum'},
        ),
        migrations.AlterField(
            model_name='sujetforum',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujetforums', to='plateforme.ThemeForum'),
        ),
    ]
